version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: persian-chatbot-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_venv:/app/venv
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:8000
      - PYTHONPATH=/app
    networks:
      - chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: persian-chatbot-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws/chat
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - chatbot-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  chatbot-network:
    driver: bridge

volumes:
  backend_venv:
  frontend_node_modules:
  frontend_next: